BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "alpha-product"
BBFILE_PATTERN_alpha-product = "^${LAYERDIR}/"
BBFILE_PRIORITY_alpha-product = "100"

LAYERDEPENDS_alpha-product = "core alpha-bsp"
LAYERSERIES_COMPAT_alpha-product = "scarthgap"
