require conf/distro/alpha.conf

DISTRO = "alpha-imx6ull-mmc"
DISTRO_NAME = "ALPHA i.MX6ULL MMC Distro"
DISTROOVERRIDES .= ":alpha-imx6ull-mmc:mx6ull:mmc"

# i.MX6ULL + MMC specific version preferences
PREFERRED_VERSION_linux-imx ?= "6.12%"
PREFERRED_VERSION_u-boot-imx ?= "2025.04%"
