require conf/machine/include/alpha-imx-base.inc

MACHINEOVERRIDES =. "imx6ull14x14alpha:mx6ull:"
ALPHA_VENDOR = "alpha"
ALPHA_PRODUCT_FAMILY = "imx6ull"

DEFAULTTUNE = "cortexa7thf-neon"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "mx6ull_14x14_alpha_mmc_defconfig,sdcard"
UBOOT_DTB_NAME = "imx6ull-14x14-alpha-mmc.dtb"
UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_MAKE_TARGET = "u-boot.imx"
UBOOT_BINARY = "u-boot.imx"
UBOOT_SUFFIX = "imx"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "nxp/imx/imx6ull-14x14-alpha-mmc.dtb"
KBUILD_DEFCONFIG = "imx6ull_14x14_alpha_mmc_defconfig"

# SD card image (WIC + sdcard symlink)
WKS_FILE = "alpha-uboot-bootpart.wks.in"
WKS_FILE_DEPENDS += " virtual/bootloader"
# Append wic/wic.bmap to the base IMAGE_FSTYPES (which already has ext4, tar.gz from distro)
IMAGE_FSTYPES:append = " wic wic.bmap"
INHERIT += "image_types_alpha"
IMAGE_BOOT_FILES ?= "${KERNEL_IMAGETYPE} imx6ull-14x14-alpha-mmc.dtb"


MACHINE_FEATURES += "usbhost usbgadget ext2 vfat"
