require conf/machine/include/alpha-imx-base.inc

MACHINEOVERRIDES =. "imx6ull14x14alpha:mx6ull:"
ALPHA_VENDOR = "alpha"
ALPHA_PRODUCT_FAMILY = "imx6ull"

DEFAULTTUNE = "cortexa7thf-neon"

UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "mx6ull_14x14_alpha_mmc_defconfig,sdcard"
UBOOT_DTB_NAME = "imx6ull-14x14-alpha-mmc.dtb"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "imx6ull-14x14-alpha-mmc.dtb"
KBUILD_DEFCONFIG = "imx6ull_14x14_alpha_mmc_defconfig"


MACHINE_FEATURES += "usbhost usbgadget ext2 vfat"
