BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "alpha-bsp"
BBFILE_PATTERN_alpha-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_alpha-bsp = "99"

LAYERDEPENDS_alpha-bsp = "core"
LAYERSERIES_COMPAT_alpha-bsp = "scarthgap"
